CONFIG_APPZIG_BASE ?= $(CURDIR)
UK_ROOT ?= $(CURDIR)/workdir/unikraft
UK_LIBS ?= $(CURDIR)/workdir/libs
UK_BUILD ?= $(CURDIR)/workdir/build
LIBS := $(UK_LIBS)/lib-musl

all:
	@$(MAKE) -C $(UK_ROOT) N=app-zig A=$(PWD) L=$(LIBS) O=$(UK_BUILD) CONFIG_APPZIG_BASE=$(CONFIG_APPZIG_BASE)

$(MAKECMDGOALS):
	@$(MAKE) -C $(UK_ROOT) N=app-zig A=$(PWD) L=$(LIBS) O=$(UK_BUILD) CONFIG_APPZIG_BASE=$(CONFIG_APPZIG_BASE) $(MAKECMDGOALS)